export const defaultSettings = {
  accountName: "未命名刊物",
  theme: "AI 工具与个体效率",
  audience: "想把 AI 真正用进工作流的职场人和独立创作者",
  tone: "有判断、讲人话、少套话；用真实场景解释复杂概念",
  author: "主理人",
  targetLength: 1800,
  referenceArticle: "",
  humanizeEnabled: true,
  designTheme: "auto",
  aiProvider: "codex",
  imageProvider: "codex",
  imageStyle: "克制的编辑插画，清晰构图，具有杂志封面的视觉张力，不出现文字与水印",
  scheduleEnabled: false,
  scheduleTime: "08:30",
  timezone: "Asia/Shanghai",
  allowComments: false,
  fansOnlyComments: false,
  evolutionRules: [
    "文章开篇 100 字内必须直接给出核心观点与结论，避免漫长铺垫",
    "标题优先采用利益引导或反常识悬念，突出读者切实收获",
  ],
  activeColumnId: "default",
  columns: [
    {
      id: "default",
      name: "主栏目",
      theme: "AI 工具与个体效率",
      audience: "想把 AI 真正用进工作流的职场人和独立创作者",
      tone: "有判断、讲人话、少套话；用真实场景解释复杂概念",
      author: "主理人",
      targetLength: 1800,
      referenceArticle: "",
      designTheme: "auto",
      aiProvider: "codex",
      imageProvider: "codex",
      imageStyle: "克制的编辑插画，清晰构图，具有杂志封面的视觉张力，不出现文字与水印",
      evolutionRules: [
        "文章开篇 100 字内必须直接给出核心观点与结论，避免漫长铺垫",
        "标题优先采用利益引导或反常识悬念，突出读者切实收获",
      ],
    },
  ],
};

export const defaultState = {
  settings: defaultSettings,
  articles: [],
  runs: [],
  scheduler: { lastRunDate: null },
};
